### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gautamsreekumar** [fengyang0317/unsupervised_captioning#1]
Some corrections and suggestions about the repo.

1. The installation instructions are confusing - whether workspace is a directory inside unsupervised-captioning or the other way. "First we refer to requirements.txt and then we clone the repo" seems wrong.
2. In preprocessing/crawl_descriptions.py, `obj = re.search('data-max="(\d*)"', page)` should be `obj = re.search('max="(\d*)"', page)`. I went through the HTML file and this is what I found (as of 8 April, 2019. The format could change later).
3. preprocessing/extract_descriptions.py imports config.py which is located in the root dir of the repo. Shouldn't this file be inside preprocessing dir. Also, the workspace dir needs maybe modified accordingly. Same with misc_fn.py
4. An error may occur while running preprocessing/extract_descriptions.py. This is a solution I found in GitHub -> [answer](https://github.com/tensorflow/models/issues/1595#issuecomment-309234210)

**Comment by fengyang0317** [comment]
I assume that you are executing the commands under "Requirements" sequentially. The unsupervised_captioning is inside workspace directory.

**Comment by gautamsreekumar** [comment]
@fengyang0317 Sorry, I was not aware I had posted the comments. I have updated my comments. Please check it again.
So what I was saying is that requirements.txt is a file inside the repo. But the repo is cloned after workspace directory is created.

**Comment by fengyang0317** [comment]
Thanks for your suggestion. I was not aware of this issue. I have updated the Requirements part.

**Comment by fresh382227905** [comment]
thanks, it does work.
