### ISSUE TITLE
No module named'data.build_mscoco_data'

### ISSUE THREAD

**Issue by zezhishao** [fengyang0317/unsupervised_captioning#13]
https://github.com/fengyang0317/unsupervised_captioning/blob/0e75b6aff4cc9e94249bc272fc5490e566ef5d7c/preprocessing/extract_descriptions.py#L16

ModuleNotFoundError: No module named 'data.build_mscoco_data'.
How can i fix it?

**Comment by BetterZH** [comment]
> https://github.com/fengyang0317/unsupervised_captioning/blob/0e75b6aff4cc9e94249bc272fc5490e566ef5d7c/preprocessing/extract_descriptions.py#L16
> 
> ModuleNotFoundError: No module named 'data.build_mscoco_data'.
> How can i fix it?

**Comment by BetterZH** [comment]
请问你解决了吗，我也没找到这个
