### ISSUE TITLE
error question

### ISSUE THREAD

**Issue by sakura2233565548** [fengyang0317/unsupervised_captioning#14]
ModuleNotFoundError: No module named 'data.build_mscoco_data'
how can I find this function?or this can be written by reader?

**Comment by fengyang0317** [comment]
Have you followed the instructions here https://github.com/fengyang0317/unsupervised_captioning#requirements?

The file is available at https://github.com/tensorflow/models/blob/master/research/im2txt/im2txt/data/build_mscoco_data.py
