### ISSUE TITLE
The passed save_path is not a valid checkpoint 

### ISSUE THREAD

**Issue by atg93** [fengyang0317/unsupervised_captioning#16]
Hi, Thank you for sharing your code. However, I countered a problem when I tried to run one of your command line on the github. When I run this command "   python test_model.py --inc_ckpt ~/workspace/ckpt/inception_v4.ckpt\
  --data_dir ~/dataset/mscoco/all_images --job_dir saving/model.ckpt-20000", it returns following error; ValueError: The passed save_path is not a valid checkpoint: saving/model.ckpt-20000. Moreover, I used your saving file in Gdrive, however there is no model.ckpt-2000, there are files like model.ckpt-2000.index and model.ckpt-2000.meta. How can I run test model using pretrained model ?

**Comment by fengyang0317** [comment]
Did you see the checkpoint files at
![image](https://user-images.githubusercontent.com/7965501/71102221-1af7c080-2186-11ea-816f-19b1a506066e.png)

**Comment by atg93** [comment]
Thank you for your answer. Yes, like I said I used your pretrained model which in your saving file, but still the code cannot find model.ckpt-2000.
