### ISSUE TITLE
Why the result of object detection of coco dataset has 545 object categories?

### ISSUE THREAD

**Issue by ZhuPeipei-CUHKSZ-TJUTCM** [fengyang0317/unsupervised_captioning#17]
As we all know, coco dataset has 80 object categories. But your code result of "object detection" of coco has 545 object categories. So, can you explain why? Thanks

**Comment by fengyang0317** [comment]
I am using the detector trained on OpenImage.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
