### ISSUE TITLE
 One Drive doesn't works

### ISSUE THREAD

**Issue by danielhv10** [fengyang0317/unsupervised_captioning#19]
Hi Yang,

 One Drive link is dead

<img width="1047" alt="Screenshot 2020-02-03 at 11 58 29" src="https://user-images.githubusercontent.com/11231994/73647814-93eea100-467c-11ea-9a8b-221e68276c3d.png">

**Comment by fengyang0317** [comment]
Sorry. The link in our school can only exist for 3 months. The following is a new one.
https://uofr-my.sharepoint.com/:f:/g/personal/yfeng23_ur_rochester_edu/EgDosCuY5t9HmlBfFsVyxdAB4xGf6aTJ0DmQlYWASdjYsw?e=GsuSkD

**Comment by danielhv10** [comment]
Thanks
