### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by ironmanx1** [fengyang0317/unsupervised_captioning#29]
$ python preprocessing/crawl_descriptions.py
person 1000
0 []
bicycle 1000
0 []
car 1000
0 []
motorbike 1000
0 []
aeroplane 1000
0 []
...
Is this result normal? How to solve it?Looking forward to your reply.

sorry to bother you,i also get the same results in this step,but i don't know change which part in crawl_descriptions.py file.Can you help me?thank you~

**Comment by fengyang0317** [comment]
Shutterstock regularly changes its APIs. The crawl script is not maintained anymore.

**Comment by ironmanx1** [comment]
very very thank you for your reply.
but i also have some questions that&nbsp;i failed to find solutions in interent yesterday.


1.Whether the&nbsp;Shutterstock's APIs are free?because i can't find its api through F12-&gt;network-&gt;scripts.


2.And if i want just crawl some images in Baidu Image instead of Shutterstock,does this work?


3.And which line in&nbsp;crawl_descriptions.py file represent the api that i want to change?Is this two lines?:


{
url = ('https://www.shutterstock.com/search?language=en&amp;image_type=photo&amp;'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'searchterm=%s&amp;page=%d')
pattern = '<script type="application/ld\+json"&gt;(\[.*\])</script&gt;'
}


sorry i know what i ask are&nbsp;naive because it is&nbsp;Not long after i join in&nbsp;Computer Industry. &nbsp;
so your help may means a lot to me.
very&nbsp;Sincerely look for you reply!
thank you again!









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengyang0317/unsupervised_captioning"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 中午11:01
收件人:&nbsp;"fengyang0317/unsupervised_captioning"<unsupervised_captioning@noreply.github.com&gt;;
抄送:&nbsp;"cxy"<793952175@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fengyang0317/unsupervised_captioning] some questions (#29)





 
Shutterstock regularly changes its APIs. The crawl script is not maintained anymore.
