### ISSUE TITLE
use the code for custom images

### ISSUE THREAD

**Issue by dami23** [fengyang0317/unsupervised_captioning#3]
First of all, thank you for the share of your code. I want to test the code on custom images,  but I can't get it working. Could you please public a demo file to test on custom images, or give me some advices to realize it? Thank you for your help!!

**Comment by fengyang0317** [comment]
https://github.com/fengyang0317/unsupervised_captioning/blob/master/eval_all.py#L63

The code here is used to test on a single image. You may change the image path there.
