### ISSUE TITLE
caption_infer

### ISSUE THREAD

**Issue by moonABC3** [fengyang0317/unsupervised_captioning#34]
After training, I try to generate some captions based on images, but why are the captions generated by different images almost the same? (I didn't change your code)

**Comment by fengyang0317** [comment]
Can you check the imge preprocessing?

**Comment by moonABC3** [comment]
I use MS COCO 2017 dataset for training. Is that the problem?

**Comment by moonABC3** [comment]
Hello, can I use your experimental data? The data can only be accessed with your permission. Thank you.
https://drive.google.com/drive/folders/1ol8gLj6hYgluldvdj9XFKm16TCqOr7EE

**Comment by fengyang0317** [comment]
I have copied the data and models to https://rochester.box.com/s/f7g31ufkp19vd6l3y9jpzf7gnjcxqxpd
and
链接: https://pan.baidu.com/s/1Z2-5I_Zn5-ox0G_GIs6Ipg 提取码: x6gk 复制这段内容后打开百度网盘手机App，操作更方便哦
