### ISSUE TITLE
I can not fetch the data and pretrained model

### ISSUE THREAD

**Issue by whqwill** [fengyang0317/unsupervised_captioning#36]
I can not fetch the data and pretrained model, any other ways?

**Comment by fengyang0317** [comment]
I have copied the data and models to https://rochester.box.com/s/f7g31ufkp19vd6l3y9jpzf7gnjcxqxpd
and
链接: https://pan.baidu.com/s/1Z2-5I_Zn5-ox0G_GIs6Ipg 提取码: x6gk 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by ukyh** [comment]
Hi, thank you for sharing the data!
I found that `image_train.tfrec` file is missing from https://rochester.box.com/s/f7g31ufkp19vd6l3y9jpzf7gnjcxqxpd.
Could you upload that data too?
Thank you!

**Comment by fengyang0317** [comment]
You need to unzip image_train.zip files to get image_train.tfrec
