### ISSUE TITLE
Input to vocabulary.py in im2txt folder

### ISSUE THREAD

**Issue by eshwarhs** [fengyang0317/unsupervised_captioning#5]
What should the input file to vocabulary.py look like? I have generated a file with a list of words in a file named "word_counts.txt" and I'm passing this to vocabulary object.

The line 
vocab = vocabulary.Vocabulary(word_counts.txt) is giving me an error I'm not able to figure out:
assert start_word in reverse_vocab
AssertionError

[word_counts.txt](https://github.com/fengyang0317/unsupervised_captioning/files/3335620/word_counts.txt)
Here's the slightly modified code
![cap](https://user-images.githubusercontent.com/45142059/60281647-ee739200-9922-11e9-9fd2-00e07206dd2e.JPG)

Someone help me out.

**Comment by fengyang0317** [comment]
<S> must be in your word_count.txt
